M48
; DRILL file {KiCad 7.0.7} date Sun Sep 10 11:25:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-10T11:25:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.1862Y-1.7226
X2.4138Y-1.7226
T2
X4.48Y-1.825
X4.4918Y-3.2817
T0
M30
